---
default_stages:
  - commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        files: \.(conf|j2|js|json|rb|md|py|sh|tf|tm?pl|txt|yaml|yml)$
      - id: check-case-conflict
      - id: end-of-file-fixer
        exclude: '^\.idea/.*$'
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.6
    hooks:
      - id: shellcheck
      - id: shfmt
        args:
          - '-w -i 2 -ci -bn -sr'
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.4.0
    hooks:
      - id: editorconfig-checker-system
        alias: ec
